zeebe:

  worker:
    defaultName: script-worker
    defaultType: script
    threads: 3

  client:
    job.timeout: 10000
    broker.contactPoint: 127.0.0.1:26500
    security.plaintext: true

logging:
  level:
    root: ERROR
    io.zeebe: INFO
    io.zeebe.script: DEBUG
